// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZKDjKMzfS0lUOkqVMVW1buTwjbPZJO0',
    appId: '1:142116989551:web:97f889e6936402a1313b9a',
    messagingSenderId: '142116989551',
    projectId: 'invotrack-d7792',
    authDomain: 'invotrack-d7792.firebaseapp.com',
    storageBucket: 'invotrack-d7792.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3yl1kvUgGI5Pu8iPU_6erGmvhWvIq5ls',
    appId: '1:142116989551:android:e52b5a4a92e112f2313b9a',
    messagingSenderId: '142116989551',
    projectId: 'invotrack-d7792',
    storageBucket: 'invotrack-d7792.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPc1BkW3jHuD8bCmDTHwF4nPXSp7uYqBk',
    appId: '1:142116989551:ios:f6f007ee644b1aaa313b9a',
    messagingSenderId: '142116989551',
    projectId: 'invotrack-d7792',
    storageBucket: 'invotrack-d7792.firebasestorage.app',
    iosBundleId: 'com.digihigh.invotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPc1BkW3jHuD8bCmDTHwF4nPXSp7uYqBk',
    appId: '1:142116989551:ios:f6f007ee644b1aaa313b9a',
    messagingSenderId: '142116989551',
    projectId: 'invotrack-d7792',
    storageBucket: 'invotrack-d7792.firebasestorage.app',
    iosBundleId: 'com.digihigh.invotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHZKDjKMzfS0lUOkqVMVW1buTwjbPZJO0',
    appId: '1:142116989551:web:6dcbf4398b824ce3313b9a',
    messagingSenderId: '142116989551',
    projectId: 'invotrack-d7792',
    authDomain: 'invotrack-d7792.firebaseapp.com',
    storageBucket: 'invotrack-d7792.firebasestorage.app',
  );
}
